services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASTRA_DB_NAMESPACE=${ASTRA_DB_NAMESPACE}
      - ASTRA_DB_COLLECTION=${ASTRA_DB_COLLECTION}
      - ASTRA_DB_API_ENDPOINT=${ASTRA_DB_API_ENDPOINT}
      - ASTRA_DB_APPLICATION_TOKEN=${ASTRA_DB_APPLICATION_TOKEN}
    volumes:
      []
    command: npm run dev